### ISSUE TITLE
About channel_distillation.py

### ISSUE THREAD

**Issue by Youskrpig** [zhouzaida/channel-distillation#4]
hello, Is self.connector really needed?

self.s_t_pair = [(256, 256), (512, 512), (1024, 1024), (2048, 2048)]
self.connector = nn.ModuleList([conv1x1_bn(s, t) for s, t in self.s_t_pair])

i found whether to use self.connector , the output dimension of student model doesn't change.

**Comment by zhouzaida** [comment]
Yes, the dimension of the student have not changed, just to make the number of channel of the student the same as the teacher

**Comment by Youskrpig** [comment]
Thanks for your reply.
