### ISSUE TITLE
question about function adjust_loss_alpha

### ISSUE THREAD

**Issue by UcanSee** [zhouzaida/channel-distillation#5]
I found weight of ce loss and kd loss is zero in first 30 epoches when training on ImageNet in your code ,(https://github.com/zhouzaida/channel-distillation/blob/2464d30ba01e11491e520e51be498c91f1e54b91/utils/util.py#L9)) 
I want to know why at the start of training, original ce loss is set to zero?

**Comment by zgcr** [comment]
> I found weight of ce loss and kd loss is zero in first 30 epoches when training on ImageNet in your code ,(
> 
> https://github.com/zhouzaida/channel-distillation/blob/2464d30ba01e11491e520e51be498c91f1e54b91/utils/util.py#L9
> 
> ))
> I want to know why at the start of training, original ce loss is set to zero?

The first 30 epochs ce loss weight is set to 0 because we want to use teacher model to initialize student model weights by using cd loss.
