### ISSUE TITLE
模型

### ISSUE THREAD

**Issue by zbh201** [zhouzaida/channel-distillation#7]
您好，请问可以提供下cifar100数据集的resnet34预训练模型吗？

**Comment by zhouzaida** [comment]
可以在这里下载https://drive.google.com/file/d/1dkBliMpojMM_ZNoT3xBHYglceaYyg_8E/view?usp=sharing

**Comment by zbh201** [comment]
> 可以在这里下载https://drive.google.com/file/d/1dkBliMpojMM_ZNoT3xBHYglceaYyg_8E/view?usp=sharing

谢谢

**Comment by zbh201** [comment]
您好，我想运行cifar100数据集下的resnet3418模型，我将cifar_train.py下的net改成了ChannelDistillResNet1834，将resnet.py下的_resnet中arch == "resnet34"时的读取改成了torch.load，model_urls中的resnet34路径改成了您发的网址下载后的模型，但是运行提示模型字典的键不对，不知道是不是因为resnet34和18采用的是BasicBlock而导致的模型结构不同，请问我还需要修改哪里？麻烦了。

**Comment by zhouzaida** [comment]
可以用cifar_train.py重新训个resnet34，因为https://drive.google.com/file/d/1dkBliMpojMM_ZNoT3xBHYglceaYyg_8E/view?usp=sharing这个模型命名和channel-distillation中的不太一致
