### ISSUE TITLE
correct_t[correct_t == 0.0] = 1.0

### ISSUE THREAD

**Issue by XiXiRuPan** [zhouzaida/channel-distillation#8]
Thanks for your sharing. I am confused with correct_t[correct_t == 0.0] = 1.0. If the prediction is wrong, why make the final probabilty is 1.0? Thanks for your reply.

**Comment by zgcr** [comment]
> Thanks for your sharing. I am confused with correct_t[correct_t == 0.0] = 1.0. If the prediction is wrong, why make the final probabilty is 1.0? Thanks for your reply.

Same question as https://github.com/zhouzaida/channel-distillation/issues/3 .I have explained the reason in this link.
